---
- name: Set Install version variable
  when: font_bizingothic_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_bizingothic_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_bizingothic_version: "{{ latest_version }}"
- name: Create BizinGothic font install directory
  ansible.builtin.file:
    path: "{{ font_dir }}/BizinGothic"
    state: directory
    mode: "0755"
- name: Install BizinGothic font
  ansible.builtin.unarchive:
    src: https://github.com/{{ font_bizingothic_repo }}/releases/download/{{ font_bizingothic_version }}/BizinGothic_{{ font_bizingothic_version }}.zip
    dest: "{{ font_dir }}/BizinGothic"
    extra_opts:
      - -j
    remote_src: true
- name: Install BizinGothic Discord font
  ansible.builtin.unarchive:
    src: https://github.com/{{ font_bizingothic_repo }}/releases/download/{{ font_bizingothic_version }}/BizinGothicDiscord_{{ font_bizingothic_version }}.zip
    dest: "{{ font_dir }}/BizinGothic"
    extra_opts:
      - -j
    remote_src: true
