---
- name: Set Install version variable
  when: font_explex_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_explex_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_explex_version: "{{ latest_version }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_file: Explex_{{ font_explex_version }}.zip
- name: Create Explex font install directory
  ansible.builtin.file:
    path: "{{ font_dir }}/Explex"
    state: directory
    mode: "0755"
- name: Install Explex font
  ansible.builtin.unarchive:
    src: https://github.com/{{ font_explex_repo }}/releases/download/{{ font_explex_version }}/{{ asset_file }}
    dest: "{{ font_dir }}/Explex"
    extra_opts:
      - -j
    remote_src: true
