---
- name: Set Install version variable
  when: font_firge_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_firge_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_firge_version: "{{ latest_version }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_file: Firge_{{ font_firge_version }}.zip
- name: Create Firge font install directory
  ansible.builtin.file:
    path: "{{ font_dir }}/Firge"
    state: directory
    mode: "0755"
- name: Install Firge font
  ansible.builtin.unarchive:
    src: https://github.com/{{ font_firge_repo }}/releases/download/{{ font_firge_version }}/{{ asset_file }}
    dest: "{{ font_dir }}/Firge"
    extra_opts:
      - -j
    remote_src: true
