---
- name: Set Install version variable
  when: font_hackgen_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_hackgen_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_hackgen_version: "{{ latest_version }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_file: HackGen_{{ font_hackgen_version }}.zip
- name: Create HackGen font install directory
  ansible.builtin.file:
    path: "{{ font_dir }}/HackGen"
    state: directory
    mode: "0755"
- name: Install HackGen font
  ansible.builtin.unarchive:
    src: https://github.com/{{ font_hackgen_repo }}/releases/download/{{ font_hackgen_version }}/{{ asset_file }}
    dest: "{{ font_dir }}/HackGen"
    extra_opts:
      - -j
    remote_src: true
