---
- name: Set Install version variable
  when: font_juisee_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_juisee_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_juisee_version: "{{ latest_version }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_url: |-
      https://github.com/{{ font_juisee_repo }}/releases/download/{{ font_juisee_version }}/Juisee_{{ font_juisee_version }}.zip
- name: Create Juisee font install directory
  ansible.builtin.file:
    path: "{{ font_dir }}/Juisee"
    state: directory
    mode: "0755"
- name: Install Juisee font
  ansible.builtin.unarchive:
    src: "{{ asset_url }}"
    dest: "{{ font_dir }}/Juisee"
    extra_opts:
      - -j
    remote_src: true
