- name: Set Install version variable
  when: font_nerd_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_nerd_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_nerd_version: "{{ latest_version }}"
- name: Include Nerd font install task
  ansible.builtin.include_tasks:
    file: tasks/custom/NerdFonts/install.yml
  loop: "{{ font_nerd_variations }}"
  loop_control:
    loop_var: variation
    label: "{{ variation }}"
