---
- name: Set Install version variable
  when: font_udevgothic_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_udevgothic_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_udevgothic_version: "{{ latest_version }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_file: UDEVGothic_{{ font_udevgothic_version }}.zip
- name: Create UDEV Gothic font install directory
  ansible.builtin.file:
    path: "{{ font_dir }}/UDEVGothic"
    state: directory
    mode: "0755"
- name: Install UDEV Gothic font
  ansible.builtin.unarchive:
    src: https://github.com/{{ font_udevgothic_repo }}/releases/download/{{ font_udevgothic_version }}/{{ asset_file }}
    dest: "{{ font_dir }}/UDEVGothic"
    extra_opts:
      - -j
    remote_src: true
