---
- name: Set Install version variable
  when: font_moralerspace_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_moralerspace_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_moralerspace_version: "{{ latest_version }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_url: |-
      https://github.com/{{ font_moralerspace_repo }}/releases/download/{{ font_moralerspace_version }}/Moralerspace_{{ font_moralerspace_version }}.zip
- name: Create Moralerspace font install directory
  ansible.builtin.file:
    path: "{{ font_dir }}/Moralerspace"
    state: directory
    mode: "0755"
- name: Install Moralerspace font
  ansible.builtin.unarchive:
    src: "{{ asset_url }}"
    dest: "{{ font_dir }}/Moralerspace"
    extra_opts:
      - -j
    remote_src: true
