---
- name: Set Install version variable
  when: font_plemoljp_version == 'latest'
  block:
    - name: Get latest version
      ansible.builtin.include_tasks:
        file: tasks/common/get_latest_version.yml
      vars:
        github_repo: "{{ font_plemoljp_repo }}"
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_plemoljp_version: "{{ latest_version }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_url: https://github.com/{{ font_plemoljp_repo }}/releases/download/{{ font_plemoljp_version }}/PlemolJP_{{ font_plemoljp_version }}.zip
- name: Create PlemolJP font install directory
  ansible.builtin.file:
    path: "{{ font_dir }}/PlemolJP"
    state: directory
    mode: "0755"
- name: Install PlemolJP font
  ansible.builtin.unarchive:
    src: "{{ asset_url }}"
    dest: "{{ font_dir }}/PlemolJP"
    extra_opts:
      - -j
    remote_src: true
